export const GROUP_TAGS = {
  PROXY: '🚀 节点选择',
  DIRECT: 'DIRECT',
  REJECT: 'REJECT',
  AD_BLOCK: '🛑 广告拦截',
  CN_SERVICES: '🔒 国内服务',
  PRIVATE_NET: '🏠 私有网络',
  NTP_SERVICES: '🕓 NTP 服务',
  BT_PT: '🧲 BT/PT',
  AI_SERVICES: '💬 AI 服务',
  YOUTUBE: '📹 油管视频',
  GOOGLE: '🔍 谷歌服务',
  TELEGRAM: '📲 电报消息',
  DEV_TOOLS: '🐱 开发工具',
  MICROSOFT: 'Ⓜ️ 微软服务',
  APPLE: '🍏 苹果服务',
  APPLE_VIDEO: '🎬 苹果视频',
  SOCIAL_MEDIA: '🌐 社交媒体',
  STREAMING: '🎬 流媒体',
  GAMING: '🎮 游戏平台',
  GAME_DOWNLOAD: '🎮 游戏下载',
  EDUCATION: '📚 教育资源',
  PRODUCTIVITY: '🛠️ 生产力工具',
  FINANCE: '💰 金融服务',
  NEWS: '📰 新闻资讯',
  ADULT: '🔞 成人内容',
  CLOUD: '☁️ 云服务',
  NON_CN: '🌐 非中国',
  SHOPPING: '🛒 购物网站',
  SPEEDTEST: '🧪 测速专线',
  FINAL: '🐟 漏网之鱼',
};

// Backwards compatibility for PROXY_SELECTOR_TAG, DIRECT_TAG, REJECT_TAG
export const PROXY_SELECTOR_TAG = GROUP_TAGS.PROXY;
export const DIRECT_TAG = GROUP_TAGS.DIRECT;
export const REJECT_TAG = GROUP_TAGS.REJECT;

export const SCENARIO_GROUPS = [
  GROUP_TAGS.SHOPPING,
  GROUP_TAGS.FINAL,
  GROUP_TAGS.SPEEDTEST,
  GROUP_TAGS.AI_SERVICES,
  GROUP_TAGS.YOUTUBE,
  GROUP_TAGS.GOOGLE,
  GROUP_TAGS.TELEGRAM,
  GROUP_TAGS.DEV_TOOLS,
  GROUP_TAGS.MICROSOFT,
  GROUP_TAGS.APPLE,
  GROUP_TAGS.APPLE_VIDEO,
  GROUP_TAGS.SOCIAL_MEDIA,
  GROUP_TAGS.STREAMING,
  GROUP_TAGS.GAMING,
  GROUP_TAGS.GAME_DOWNLOAD,
  GROUP_TAGS.EDUCATION,
  GROUP_TAGS.PRODUCTIVITY,
  GROUP_TAGS.FINANCE,
  GROUP_TAGS.NEWS,
  GROUP_TAGS.ADULT,
  GROUP_TAGS.CLOUD,
  GROUP_TAGS.NON_CN
];

export const CORE_GROUPS = [
  GROUP_TAGS.CN_SERVICES,
  GROUP_TAGS.AD_BLOCK,
  GROUP_TAGS.DIRECT,
  GROUP_TAGS.REJECT,
  GROUP_TAGS.PROXY
];

export const DIRECT_REDIRECT_GROUPS = [
  GROUP_TAGS.BT_PT,
  GROUP_TAGS.PRIVATE_NET,
  GROUP_TAGS.NTP_SERVICES
];
