import { GroupDefinition, RouteRuleDefinition, RuleSetDefinition, DIRECT_TAG } from './types';

export const REGION_DEFINITIONS: Array<{ code: string; tag: string }> = [
  { code: 'HK', tag: '🇭🇰 香港节点' },
  { code: 'US', tag: '🇺🇸 美国节点' },
  { code: 'JP', tag: '🇯🇵 日本节点' },
  { code: 'SG', tag: '🇸🇬 新加坡节点' },
  { code: 'TW', tag: '🇼🇸 台湾节点' },
];

export const RULE_SET_DEFINITIONS: RuleSetDefinition[] = [
  { kind: 'geosite', tag: 'advertising', remoteName: 'category-ads-all' },
  {
    kind: 'geosite',
    tag: 'adblockfilters',
    url: 'https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblocksingbox.srs',
  },
  { kind: 'geosite', tag: 'geolocation-cn' },
  { kind: 'geosite', tag: 'geolocation-!cn' },
  { kind: 'geosite', tag: 'cn' },
  { kind: 'geoip', tag: 'cn-ip', remoteName: 'cn' },
  { kind: 'geosite', tag: 'private' },
  { kind: 'geoip', tag: 'private-ip', remoteName: 'private' },
  { kind: 'geosite', tag: 'category-antivirus' },
  { kind: 'geosite', tag: 'win-update' },
  { kind: 'geosite', tag: 'category-speedtest' },
  { kind: 'geosite', tag: 'category-ntp' },
  { kind: 'geosite', tag: 'category-ai-chat-!cn' },
  { kind: 'geosite', tag: 'xai' },
  { kind: 'geosite', tag: 'cursor' },
  { kind: 'geosite', tag: 'windsurf' },
  { kind: 'geosite', tag: 'trae' },
  { kind: 'geosite', tag: 'manus' },
  { kind: 'geosite', tag: 'jetbrains-ai' },
  { kind: 'geosite', tag: 'youtube' },
  { kind: 'geosite', tag: 'netflix' },
  { kind: 'geoip', tag: 'netflix-ip', remoteName: 'netflix' },
  { kind: 'geosite', tag: 'disney' },
  { kind: 'geosite', tag: 'hbo' },
  { kind: 'geosite', tag: 'hulu' },
  { kind: 'geosite', tag: 'primevideo' },
  { kind: 'geosite', tag: 'category-entertainment@!cn' },
  { kind: 'geosite', tag: 'apple' },
  { kind: 'geosite', tag: 'appletv', remoteName: 'apple-tvplus' },
  { kind: 'geosite', tag: 'google' },
  { kind: 'geoip', tag: 'google-ip', remoteName: 'google' },
  { kind: 'geosite', tag: 'apple-cn' },
  { kind: 'geosite', tag: 'google-cn' },
  { kind: 'geosite', tag: 'category-games@cn' },
  { kind: 'geosite', tag: 'microsoft' },
  { kind: 'geosite', tag: 'category-dev' },
  { kind: 'geosite', tag: 'category-container' },
  { kind: 'geosite', tag: 'microsoft-dev' },
  { kind: 'geosite', tag: 'jetbrains' },
  { kind: 'geosite', tag: 'gitlab' },
  { kind: 'geosite', tag: 'category-communication' },
  { kind: 'geosite', tag: 'category-voip' },
  { kind: 'geoip', tag: 'telegram-ip', remoteName: 'telegram' },
  { kind: 'geosite', tag: 'category-forums' },
  { kind: 'geosite', tag: 'category-social-media-!cn' },
  { kind: 'geoip', tag: 'twitter-ip', remoteName: 'twitter' },
  { kind: 'geosite', tag: 'category-games-!cn' },
  { kind: 'geosite', tag: 'category-game-platforms-download' },
  { kind: 'geosite', tag: 'category-scholar-!cn' },
  { kind: 'geosite', tag: 'category-remote-control' },
  { kind: 'geosite', tag: 'category-password-management' },
  { kind: 'geosite', tag: 'tutanota' },
  { kind: 'geosite', tag: 'category-cryptocurrency' },
  { kind: 'geosite', tag: 'paypal' },
  { kind: 'geosite', tag: 'category-finance' },
  { kind: 'geosite', tag: 'category-tech-media' },
  { kind: 'geosite', tag: 'category-news-ir' },
  { kind: 'geosite', tag: 'category-porn' },
  { kind: 'geosite', tag: 'category-public-tracker' },
  { kind: 'geosite', tag: 'category-pt' },
  { kind: 'geosite', tag: 'cloudflare' },
  { kind: 'geoip', tag: 'cloudflare-ip', remoteName: 'cloudflare' },
  { kind: 'geosite', tag: 'dropbox' },
  { kind: 'geosite', tag: 'mega' },
  { kind: 'geosite', tag: 'microsoft@cn' },
  { kind: 'geosite', tag: 'steam@cn' },
  { kind: 'geosite', tag: 'onedrive' },
  { kind: 'geosite', tag: 'category-netdisk-!cn' },
  { kind: 'geosite', tag: 'category-netdisk-cn' },
  { kind: 'geosite', tag: 'category-ecommerce' },
  { kind: 'geosite', tag: 'category-ecommerce@cn' },
  { kind: 'geosite', tag: 'category-collaborate-cn' },
  { kind: 'geosite', tag: 'category-cdn-cn' },
  { kind: 'geosite', tag: 'category-ip-geo-detect' },
  { kind: 'geosite', tag: 'category-android-app-download' },
  { kind: 'geosite', tag: 'category-scholar-cn' },
  { kind: 'geosite', tag: 'category-bank-cn' },
  { kind: 'geosite', tag: 'category-ai-cn' },
];

export const ROUTE_RULES: RouteRuleDefinition[] = [
  { action: 'sniff' },
  {
    type: 'logical',
    mode: 'or',
    rules: [{ protocol: 'dns' }, { port: 53 }],
    action: 'hijack-dns',
  },
  { port: 22, action: 'route', outbound: DIRECT_TAG },
  { port: 11010, action: 'route', outbound: DIRECT_TAG },
  { rule_set: 'private-ip', action: 'route', outbound: '🏠 私有网络' },
  { rule_set: 'private', action: 'route', outbound: '🏠 私有网络' },
  { domain_suffix: ['et.net', 'ts.net'], action: 'route', outbound: DIRECT_TAG },
  { rule_set: 'advertising', action: 'route', outbound: '🛑 广告拦截' },
  { rule_set: 'adblockfilters', action: 'route', outbound: '🛑 广告拦截' },
  { rule_set: 'geolocation-cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'cn-ip', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'category-antivirus', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'win-update', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'apple-cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'google-cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'microsoft@cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'steam@cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'onedrive', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'category-netdisk-cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'category-ecommerce@cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'category-collaborate-cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'category-cdn-cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'category-scholar-cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'category-bank-cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'category-games@cn', action: 'route', outbound: '🔒 国内服务' },
  { rule_set: 'category-speedtest', action: 'route', outbound: '🧪 测速专线' },
  { rule_set: 'category-ntp', action: 'route', outbound: '🕓 NTP 服务' },
  { rule_set: 'category-dev', action: 'route', outbound: '🐱 开发工具' },
  { rule_set: 'category-container', action: 'route', outbound: '🐱 开发工具' },
  { rule_set: 'microsoft-dev', action: 'route', outbound: '🐱 开发工具' },
  { rule_set: 'jetbrains', action: 'route', outbound: '🐱 开发工具' },
  { rule_set: 'gitlab', action: 'route', outbound: '🐱 开发工具' },
  { rule_set: 'google', action: 'route', outbound: '🔍 谷歌服务' },
  { rule_set: 'google-ip', action: 'route', outbound: '🔍 谷歌服务' },
  { rule_set: 'appletv', action: 'route', outbound: '🎬 苹果视频' },
  { rule_set: 'apple', action: 'route', outbound: '🍏 苹果服务' },
  { rule_set: 'microsoft', action: 'route', outbound: 'Ⓜ️ 微软服务' },
  { rule_set: 'category-ai-chat-!cn', action: 'route', outbound: '💬 AI 服务' },
  { rule_set: 'xai', action: 'route', outbound: '💬 AI 服务' },
  { rule_set: 'cursor', action: 'route', outbound: '💬 AI 服务' },
  { rule_set: 'windsurf', action: 'route', outbound: '💬 AI 服务' },
  { rule_set: 'trae', action: 'route', outbound: '💬 AI 服务' },
  { rule_set: 'manus', action: 'route', outbound: '💬 AI 服务' },
  { rule_set: 'jetbrains-ai', action: 'route', outbound: '💬 AI 服务' },
  { rule_set: 'category-communication', action: 'route', outbound: '📲 电报消息' },
  { rule_set: 'category-voip', action: 'route', outbound: '📲 电报消息' },
  { rule_set: 'telegram-ip', action: 'route', outbound: '📲 电报消息' },
  { rule_set: 'youtube', action: 'route', outbound: '📹 油管视频' },
  { rule_set: 'netflix', action: 'route', outbound: '🎬 流媒体' },
  { rule_set: 'netflix-ip', action: 'route', outbound: '🎬 流媒体' },
  { rule_set: 'disney', action: 'route', outbound: '🎬 流媒体' },
  { rule_set: 'hbo', action: 'route', outbound: '🎬 流媒体' },
  { rule_set: 'hulu', action: 'route', outbound: '🎬 流媒体' },
  { rule_set: 'primevideo', action: 'route', outbound: '🎬 流媒体' },
  { rule_set: 'category-entertainment@!cn', action: 'route', outbound: '🎬 流媒体' },
  { rule_set: 'category-forums', action: 'route', outbound: '🌐 社交媒体' },
  { rule_set: 'category-social-media-!cn', action: 'route', outbound: '🌐 社交媒体' },
  { rule_set: 'twitter-ip', action: 'route', outbound: '🌐 社交媒体' },
  { rule_set: 'category-game-platforms-download', action: 'route', outbound: '🎮 游戏下载' },
  { rule_set: 'category-games-!cn', action: 'route', outbound: '🎮 游戏平台' },
  { rule_set: 'category-scholar-!cn', action: 'route', outbound: '📚 教育资源' },
  { rule_set: 'category-remote-control', action: 'route', outbound: '🛠️ 生产力工具' },
  { rule_set: 'category-password-management', action: 'route', outbound: '🛠️ 生产力工具' },
  { rule_set: 'tutanota', action: 'route', outbound: '🛠️ 生产力工具' },
  { rule_set: 'category-cryptocurrency', action: 'route', outbound: '💰 金融服务' },
  { rule_set: 'paypal', action: 'route', outbound: '💰 金融服务' },
  { rule_set: 'category-finance', action: 'route', outbound: '💰 金融服务' },
  { rule_set: 'category-tech-media', action: 'route', outbound: '📰 新闻资讯' },
  { rule_set: 'category-news-ir', action: 'route', outbound: '📰 新闻资讯' },
  { rule_set: 'category-porn', action: 'route', outbound: '🔞 成人内容' },
  { rule_set: 'category-public-tracker', action: 'route', outbound: '🧲 BT/PT' },
  { rule_set: 'category-pt', action: 'route', outbound: '🧲 BT/PT' },
  { rule_set: 'cloudflare', action: 'route', outbound: '☁️ 云服务' },
  { rule_set: 'cloudflare-ip', action: 'route', outbound: '☁️ 云服务' },
  { rule_set: 'category-netdisk-!cn', action: 'route', outbound: '☁️ 云服务' },
  { rule_set: 'category-android-app-download', action: 'route', outbound: '☁️ 云服务' },
  { rule_set: 'dropbox', action: 'route', outbound: '☁️ 云服务' },
  { rule_set: 'mega', action: 'route', outbound: '☁️ 云服务' },
  { rule_set: 'category-ecommerce', action: 'route', outbound: '🛒 购物网站' },
  { rule_set: 'category-ip-geo-detect', action: 'route', outbound: '🧪 测速专线' },
  { rule_set: 'geolocation-!cn', action: 'route', outbound: '🌐 非中国' },
];

export const GROUP_DEFINITIONS: GroupDefinition[] = [
  { tag: '🔒 国内服务', layout: 'direct-main' },
  { tag: '🏠 私有网络', layout: 'direct-main' },
  { tag: '🛑 广告拦截', layout: 'block-first' },
  { tag: '🕓 NTP 服务', layout: 'direct-main' },
  { tag: '🔍 谷歌服务', layout: 'main-direct' },
  { tag: '🎬 苹果视频', layout: 'main-direct' },
  { tag: '🍏 苹果服务', layout: 'main-direct' },
  { tag: 'Ⓜ️ 微软服务', layout: 'main-direct' },
  { tag: '💬 AI 服务', layout: 'main-direct' },
  { tag: '📹 油管视频', layout: 'main-direct' },
  { tag: '🎬 流媒体', layout: 'main-direct' },
  { tag: '🌐 社交媒体', layout: 'main-direct' },
  { tag: '🎮 游戏平台', layout: 'main-direct' },
  { tag: '🎮 游戏下载', layout: 'main-direct' },
  { tag: '📚 教育资源', layout: 'main-direct' },
  { tag: '🛠️ 生产力工具', layout: 'main-direct' },
  { tag: '💰 金融服务', layout: 'main-direct' },
  { tag: '📰 新闻资讯', layout: 'main-direct' },
  { tag: '🔞 成人内容', layout: 'main-direct' },
  { tag: '🧲 BT/PT', layout: 'main-direct' },
  { tag: '🐱 开发工具', layout: 'main-direct' },
  { tag: '🛒 购物网站', layout: 'main-direct' },
  { tag: '☁️ 云服务', layout: 'main-direct' },
  { tag: '🧪 测速专线', layout: 'main-direct' },
  { tag: '🌐 非中国', layout: 'main-direct' },
  { tag: '🐟 漏网之鱼', layout: 'main-direct' },
];
